site_name: Timewell Tech Docs
site_url: https://docs.timewelltech.ca/
site_author: Shawn Timewell
copyright: Copyright &copy; 2022 - 2023 Timewell Tech
repo_name: stim-ca/docs.timewelltech.ca
repo_url: https://github.com/stim-ca/docs.timewelltech.ca

theme:
  name: material
  custom_dir: overrides

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: timewelltech
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: false
      enabled: true

markdown_extensions:
  - markdown.extensions.abbr
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra:
  analytics:
    provider: custom
    property: plausible

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stim-ca
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/timewelltech
    - icon: fontawesome/solid/globe
      link: https://timewelltech.ca/
    - icon: fontawesome/solid/blog
      link: https://blog.timewelltech.ca

extra_css:
  - stylesheets/extra.css